-- DROP TABLE --
DROP TABLE TEST;
DROP TABLE QUESTION;
DROP TABLE CHOICEITEM;
DROP TABLE CUSTOMER;
DROP TABLE TESTRESULT;
DROP TABLE QUESTIONRESULT;

-- CREATE TABLE --
CREATE TABLE TEST (
	TT_ID  BIGINT AUTO_INCREMENT PRIMARY KEY,
	TT_NAME VARCHAR(80) NOT NULL,
	TT_NUMQUESTION INTEGER NOT NULL,
	TT_TIMELIMITMIN INTEGER NOT NULL,
	TT_DESCRIPTION VARCHAR(255) NULL,
	TT_SCORE INTEGER NULL
);


CREATE TABLE QUESTION (
	QN_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	QN_NAME VARCHAR(512) NOT NULL,
	QN_ANSWER VARCHAR(512) NULL,
	QN_SCORE INTEGER NULL,
	QN_TEST_ID BIGINT NULL,
	FOREIGN KEY(QN_TEST_ID) REFERENCES TEST(TT_ID)
);

CREATE TABLE CHOICEITEM (
	CM_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	CM_NAME VARCHAR(512) NOT NULL,
	CM_CORRECT INTEGER DEFAULT 0 NULL,
	CM_QUESTION_ID BIGINT NULL,
	FOREIGN KEY(CM_QUESTION_ID) REFERENCES QUESTION(QN_ID)
);

CREATE TABLE CUSTOMER (
	CR_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	CR_USERID VARCHAR(255) NOT NULL,
	CR_PASSWORD VARCHAR(255) NOT NULL,
	CR_EMAIL VARCHAR(255) NULL
);

CREATE TABLE TESTRESULT (
	TR_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	TR_CUSTOMERID BIGINT NOT NULL,
	TR_SCORE INTEGER NOT NULL,
	TR_RESULT INTEGER NOT NULL,
	TR_STARTTIME TIMESTAMP NULL,
	TR_ENDTIME TIMESTAMP NULL,
	TR_STATUE INTEGER NULL,
	TR_TEST_ID BIGINT NOT NULL,
	FOREIGN KEY(TR_CUSTOMERID) REFERENCES CUSTOMER(CR_ID),
	FOREIGN KEY(TR_TEST_ID) REFERENCES TEST(TT_ID)
);

CREATE TABLE QUESTIONRESULT (
	QR_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	QR_SCORE INTEGER NOT NULL,
	QR_ANSWER VARCHAR(512) NULL,
	QR_RESULT INTEGER NOT NULL,
	QR_TESTRESULT_ID BIGINT NULL,
	QR_QUESTION_ID BIGINT NULL,
	FOREIGN KEY(QR_TESTRESULT_ID) REFERENCES TESTRESULT(TR_ID),
	FOREIGN KEY(QR_QUESTION_ID) REFERENCES QUESTION(QN_ID)
);

-- CLEAR TABLE --
DELETE FROM CHOICEITEM;
DELETE FROM QUESTION;
DELETE FROM TEST; 
DELETE FROM QUESTIONRESULT;
DELETE FROM TESTRESULT;
DELETE FROM CUSTOMER;